
name: Build and deploy parking

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs: 

  build:
    runs-on: self-hosted #ubuntu-latest ejecuta en la nube
    steps:
    - uses: actions/checkout@v4

    # - name: apt update
    #   run: sudo apt update
    # - name: install bun js
    #   run: sudo snap install bun-js
    # - name: install go
    #   run: sudo snap install go --classic

    # - name: Install dependencies frontend
    #   run: cd web && bun install

    # - name: Install dependencies backend
    #   run: go mod tidy

    # - name: Build frontend and backend
    #   run: bash push.sh b

    # - name: Remove all files
    #   run:  mkdir /tmp/files && cp Dockerfile sis docker-compose.yaml /tmp/files/ && rm -rf * && cp /tmp/files/* . && rm -rf /tmp/files
  
  deploy:
    runs-on: self-hosted
    needs: build 
    steps:
    - name: build image
      run: docker compose build 
    # - name: Stop services
    #   run: docker compose stop
    - name: deploy
      run: docker compose up -d --build
